### ISSUE TITLE
Website Ideas

### ISSUE THREAD

**Issue by MylesBorins** [Open-Web-Conf/Toronto-2016#3]
I know we are a bunch of awesome engineers hurrr... but should there be budget set aside for a website?

Things that could cost money
- Hosting
- Domain
- cdn
- UI / UX design + comps / wireframes
- Branding + Logo (could be tied to above)
- Implementation ~ HTML / CSS / js

**Comment by TheAlphaNerd** [comment]
If those involved in the conf want to volunteer for this stuff that is pretty awesome... but I think we need to be very honest about our time early and figure out if we need to budget for any of this stuff

**Comment by darcyclarke** [comment]
This is definitely a place where I'd rather not spend money. Even if it kills me, I'll make a website myself if I have to. I think we can source a lot of design assets etc. as well.

**Comment by TheAlphaNerd** [comment]
Cool beans. I would suggest getting some of the base done ASAP... being blocked by the website is a total buzzkill

**Comment by jeffjewiss** [comment]
I've seen jsconf referenced a few times and their site seems to be hosted by GitHub pages: https://github.com/jsconf/jsconfus2015

Since the rest of the conference discussion is being done in the open, should the website be designed and developed in the open as much as possible? That would take care of hosting and cdn and then a it would just need a subdomain pointing to it.

**Comment by jwilkinson** [comment]
You may want to also look into integrating with Lanyard. Full Stack Toronto used the Lanyard API to power the schedule.

**Comment by darcyclarke** [comment]
@jwilkinson Lanyard integration would be awesome! It's definitely still my personal goto for updates on conferences

**Comment by ahmadnassri** [comment]
github pages with something like [Jekyll](http://jekyllrb.com/) or [Metalsmith](http://www.metalsmith.io/) would make it cheap and easy to integrate with Lanyard.

add Cloudflare for caching and you get free SSL which benefits SEO as well.

**Comment by TheAlphaNerd** [comment]
I had great luck with jade + stylus for a super minimal and simple static website for jQuerySF

https://github.com/jQuerySF/2015.jquerysf.com
